# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Generate Cypress Report

on:
  push:
    branches: [ "main" ]

jobs:
  cypress-test:
    name: Runs on Chrome
    runs-on: ubuntu-22.04
    container: cypress/browsers:node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
      run: npm ci

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome

    - name: Copy Execution Videos and Screenshots
      run: |
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots

    - name: Merge Test Reports
      run: npm run report:merge

    - name: Generate HTML Report
      run: npm run report:generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
